### ISSUE TITLE
AttributeError insert_dlcs

### ISSUE THREAD

**Issue by Halavus** [olescheller/anno1800-retroactive-dlc-activation#5]
I've got this error

`Exception in Tkinter callback

Traceback (most recent call last):
  File "tkinter\__init__.py", line 1948, in __call__
  File "a1800da\gui.py", line 45, in apply_changes
AttributeError: 'NoneType' object has no attribute 'insert_dlcs'`

I know very few of python, but is GameSetupWriter imported correctly?

**Comment by olescheller** [comment]
This looks to be a duplicate of #4. See my comment on the problem here: https://github.com/olescheller/anno1800-retroactive-dlc-activation/issues/4#issuecomment-1484197359
